# -*- coding: utf-8 -*-
"""GMC Python Class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRv2xuvtIhkdWk6nmdmXZsrD2v7hiNzg

#First Python Class
##Python is case sensitive
`print` is a built-in function
"""

print("Hello World")

print("my name is Raechelle Gerard")

